# Generated by Django 3.1.4 on 2020-12-22 01:44

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('folder_file', '0003_auto_20201222_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='folder_file.file'),
        ),
    ]
